### PR TITLE
force ABI update

### PR DESCRIPTION
**Pull request by MarshallOfSound**

### CODE REVIEW

**Comment by vecerek** [comment]
@MarshallOfSound I believe this PR broke master. Although, I don't fully understand yet why.
```sh
fnm use 10
yarn test # this fails with the error message seen in the Travis build for node <= v10, succeeds with node 12+
git checkout HEAD~1
yarn test # this succeeds
```

**Comment by MarshallOfSound** [comment]
I don't see how that could happen lol, this PR just changed a single line in the registry (through the automated script)

**Comment by vecerek** [comment]
There's something weird going on with sorting in node <= 10. I'm referring to these lines: https://github.com/lgeiger/node-abi/blob/master/index.js#L92-L94.

**Comment by vecerek** [comment]
@MarshallOfSound https://github.com/lgeiger/node-abi/pull/99

**Pull request merged**
