### PR TITLE
Add all versions of node/electron & use semver (attempt 2)

### PR DESCRIPTION
**Pull request by fanatid**
Previous PR: #18 
This PR do not need major version bump

### CODE REVIEW

**Comment by fanatid** [comment]
ping :)

**Comment by lgeiger** [comment]
Sorry for the long wait, I'll try to take a look next week.

**Comment by lgeiger** [comment]
Hi @fanatid thanks again for your effort! 👍 
This adds a lot of complexity to the module. Personally I like to keep the simplicity of the module as is.

The automatic updating of the list is awesome. But for me I think it adds a bit too much complexity to `node-abi`. At the moment we can just update the list from the GitHub UI on every Node major and every Electron minor version which can be done quite fast.

I don't like the idea of maintaining a complete list of all Node and Electron version (including patch releases) since it would almost always be outdated. We use this module for rebuilding native packages against different ABIs. Therefore we only care about the releases that have an ABI change. What is your use case where you need all the available targets?

**Comment by lgeiger** [comment]
Closing in favor of #12 

Thanks again for your work.

**Pull request closed without merging**
