### PR TITLE
Add Electron 2.0.0(-beta.1) to future targets

### PR DESCRIPTION
**Pull request by jacobq**
Closes https://github.com/lgeiger/node-abi/issues/36

### CODE REVIEW

**Comment by jacobq** [comment]
FYI, this does seem to work for me. I just added the following to my `package.json` and ran `yarn` then was able to build & run the app again:
```
  "resolutions": {
    "node-abi": "git+ssh://git@github.com/jacobq/node-abi#feat/support-electron-2.0.0-beta.1"
  }
```

**Comment by jacobq** [comment]
I don't quite understand why this is, but it seems to work regardless of whether I use '57' ([per Node 8.9.x](https://nodejs.org/en/download/releases/)) or '61' ([per Chrome version](https://electronjs.org/releases#2.0.0-beta.1))

**Comment by javan** [comment]
I don't know the answer to your question, but I was able to test this change using the current node-abi release and adding the target manually:
```js
const nodeAbi = require('node-abi')
nodeAbi.allTargets.push({runtime: 'electron', target: '2.0.0', abi: '57', lts: false})
```
👌

**Comment by MarshallOfSound** [comment]
Module version number is correct and this passes all current tests. Gonna merge this to unblock a bunch of folks 👍

**Comment by lgeiger** [comment]
Excellent thanks 👍

**Pull request merged**
